# Generated by Django 3.2.9 on 2021-12-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctorlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=15)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('pmdc', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='patientlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=15)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='makeappointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('paymentmethod', models.CharField(max_length=30)),
                ('appoointmentstatus', models.CharField(max_length=15)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='call.doctorlogin')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='call.patientlogin')),
            ],
        ),
        migrations.CreateModel(
            name='jazzcash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('patientid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.patientlogin')),
            ],
        ),
        migrations.CreateModel(
            name='easypaisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('patientid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.patientlogin')),
            ],
        ),
        migrations.CreateModel(
            name='doctorjazzcash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('doctorid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.doctorlogin')),
            ],
        ),
        migrations.CreateModel(
            name='doctoreasypaisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('doctorid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.doctorlogin')),
            ],
        ),
        migrations.CreateModel(
            name='doctorcreditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cardbrand', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=16)),
                ('expirydate', models.DateField()),
                ('CVV', models.CharField(max_length=3)),
                ('doctorid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.doctorlogin')),
            ],
        ),
        migrations.CreateModel(
            name='creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cardbrand', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=16)),
                ('expirydate', models.DateField()),
                ('CVV', models.CharField(max_length=3)),
                ('patientid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='call.patientlogin')),
            ],
        ),
    ]
